version: '3'
services:

  # MySQL, MongoDB, Redis
  mysql:
    image: mysql:latest
<<<<<<< HEAD
    ports:
      - "33690:33690"
=======
<<<<<<< HEAD
    ports:
      - "33690:33690"
=======
    ports: "33690:33690"
>>>>>>> gateway-dev
>>>>>>> auth-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Ekrvnf11'
      TZ: 'Asia/Seoul'
  
  mongo:
    image: mongo:latest
<<<<<<< HEAD
    ports:
      - "33691:33691"
=======
<<<<<<< HEAD
    ports:
      - "33691:33691"
=======
    ports: "33691:33691"
>>>>>>> gateway-dev
>>>>>>> auth-dev
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: e201
      MONGO_INITDB_ROOT_PASSWORD: Ekrvnf11

  redis:
    image: redis:latest
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> auth-dev
    ports:
      - "33692:33692"
    restart: always

  # gateway, discovery, config
  gateway:
<<<<<<< HEAD
=======
=======
    ports: "33692:33692"
    restart: always

  # gateway, discovery, config
  gateway-server:
>>>>>>> gateway-dev
>>>>>>> auth-dev
    build:
      context: gateway
      dockerfile: Dockerfile
    container_name: gateway
    image: gateway-server
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> auth-dev
    ports: 
      - "17650:17650"

  discovery:
<<<<<<< HEAD
=======
=======
    ports: "17650:17650"

  discovery-server:
>>>>>>> gateway-dev
>>>>>>> auth-dev
    build:
      context: discovery
      dockerfile: Dockerfile
    container_name: discovery
    image: discovery-server
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> auth-dev
    ports:
      - "17651:17651"
  
  config:
<<<<<<< HEAD
=======
=======
    ports: "17651:17651"
  
  config-server:
>>>>>>> gateway-dev
>>>>>>> auth-dev
    build:
      context: config
      dockerfile: Dockerfile
    container_name: config
    image: config-server
<<<<<<< HEAD
    ports:
      - "17652:17652"
=======
<<<<<<< HEAD
    ports:
      - "17652:17652"
=======
    ports: "17652:17652"
>>>>>>> gateway-dev
>>>>>>> auth-dev

  # Auth Service Server
  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    container_name: auth
    image: auth-service
<<<<<<< HEAD
    ports:
      - "52711:52711"
=======
<<<<<<< HEAD
    ports:
      - "52711:52711"
=======
    ports: "52711:52711"
>>>>>>> gateway-dev
>>>>>>> auth-dev
    depends_on:
      - mysql
      - redis

  # Mountain Service Server
  mountain:
    build:
      context: mountain
      dockerfile: Dockerfile
    container_name: mountain
    image: mountain-service
<<<<<<< HEAD
    ports:
      - "52712:52712"
=======
<<<<<<< HEAD
    ports:
      - "52712:52712"
=======
    ports: "52712:52712"
>>>>>>> gateway-dev
>>>>>>> auth-dev
    depends_on:
      - mysql

  # Guild Service Server
  guild:
    build:
      context: guild
      dockerfile: Dockerfile
    container_name: guild
    image: guild-service
<<<<<<< HEAD
    ports:
      - "52713:52713"
=======
<<<<<<< HEAD
    ports:
      - "52713:52713"
=======
    ports: "52713:52713"
>>>>>>> gateway-dev
>>>>>>> auth-dev
    depends_on:
      - mysql
      - redis
      - mongo

  # Party Service Server
  party:
    build:
      context: party
      dockerfile: Dockerfile
    container_name: party
    image: party-service
<<<<<<< HEAD
    ports:
      - "52714:52714"
=======
<<<<<<< HEAD
    ports:
      - "52714:52714"
=======
    ports: "52714:52714"
>>>>>>> gateway-dev
>>>>>>> auth-dev
    depends_on:
      - mysql
      - mongo

  # Hiking Service Server
  hiking:
    build:
      context: hiking
      dockerfile: Dockerfile
    container_name: hiking
    image: hiking-service
<<<<<<< HEAD
    ports:
      - "52715:52715"
=======
<<<<<<< HEAD
    ports:
      - "52715:52715"
=======
    ports: "52715:52715"
>>>>>>> gateway-dev
>>>>>>> auth-dev
    depends_on:
      - redis

  # Community Service Server
  community:
    build:
      context: community
      dockerfile: Dockerfile
    container_name: community
    image: community-service
<<<<<<< HEAD
    ports:
      - "52716:52716"
=======
<<<<<<< HEAD
    ports:
      - "52716:52716"
=======
    ports: "52716:52716"
>>>>>>> gateway-dev
>>>>>>> auth-dev
    depends_on:
      - mysql

  # Common Service Server
  common:
    build:
      context: common
      dockerfile: Dockerfile
    container_name: common
    image: common-service
<<<<<<< HEAD
    ports:
      - "52717:52717"
=======
<<<<<<< HEAD
    ports:
      - "52717:52717"
=======
    ports: "52717:52717"
>>>>>>> gateway-dev
>>>>>>> auth-dev
    depends_on:
      - mysql

networks:
  sdnetwork:
<<<<<<< HEAD
    external: true
=======
<<<<<<< HEAD
    external: true
=======
    external: true
>>>>>>> gateway-dev
>>>>>>> auth-dev
