server:
  port: 17650

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
      routes:
        - id: auth
          uri: http://localhost:52711/
          predicates:
            - Path=/api/auth/**
          filters:
            - CustomFilter
        - id: mountain
          uri: http://localhost:52712/
          predicates:
            - Path=/api/mountain/**
          filters:
            - CustomFilter
        - id: guild
          uri: http://localhost:52713/
          predicates:
            - Path=/api/guild/**
          filters:
            - CustomFilter
        - id: party
          uri: http://localhost:52714/
          predicates:
            - Path=/api/party/**
          filters:
            - CustomFilter
        - id: hiking
          uri: http://localhost:52715/
          predicates:
            - Path=/api/hiking/**
          filters:
            - CustomFilter
        - id: community
          uri: http://localhost:52716/
          predicates:
            - Path=/api/community/**
          filters:
            - CustomFilter

logging:
  level:
    root: info
    org.springframework.cloud.gateway: debug
    com.santeut.gateway: debug
