server:
  port: 9000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - CustomFilter
#            - AddRequestHeader=auth-request, auth-request-header
#            - AddResponseHeader=auth-response, auth-response-header
#        - id: mountain
#          uri: http://localhost:8082
#          predicates:
#            - Path=/mountain/**
#        - id: guild
#          uri: http://localhost:8083
#          predicates:
#            - Path=/guild/**
#        - id: party
#          uri: http://localhost:8084
#          predicates:
#            - Path=/party/**
#        - id: hiking
#          uri: http://localhost:8085
#          predicates:
#            - Path=/hiking/**
#        - id: community
#          uri: http://localhost:8086
#          predicates:
#            - Path=/community/**
logging:
  level:
    root: info
    org.hibernate:
      sql: debug
      type.type.descriptor.sql: trace
    com.santeut.gateway: debug
